apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-dm
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sfs
spec:
  selector:
    matchLabels:
      app: mongo-dm
  serviceName: mongo-svc
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: mongo-dm
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
         podAntiAffinity: 
           requiredDuringSchedulingIgnoredDuringExecution: 
           - labelSelector: 
               matchExpressions: 
               - key: "app"
                 operator: In
                 values:
                 - mongo
             topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mongo-pod
        image: mongo
        command:
        - mongod
        - "--bind_ip_all"
        - "--replSet"
        - rs0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ibmc-file-bronze
      resources:
        requests:
          storage: 20Gi