apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-cm
  namespace: dev1
data:
  mongo.conf: |
    systemLog:
      destination: file
      path: "/var/log/mongodb/mongodb.log"
      logAppend: true
    processManagement:
      fork: false
    net:
      port: 27017
      bindIp: 0.0.0.0
    security:
    #  keyFile: "/tmp/mongo-secret/secret-key/key"
      authorization: disabled
    storage:
      dbPath: /var/lib/mongodb
    setParameter:
      enableLocalhostAuthBypass: true
      authenticationMechanisms: SCRAM-SHA-1
  mongos: |
    MONGOS_EXEC="/usr/bin/mongos"
    MONGOS_RUN="/var/run/mongodb"
    MONGOS_USER="mongodb"
    MONGOS_IP="127.0.0.1"
    MONGOS_PORT="27018"
    MONGOS_CONFIGDB=""
    MONGOS_OPTIONS=""