apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: dev1
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-dm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-sfs
  namespace: dev1
spec:
  serviceName: mongo-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-dm
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo-con
        image: docker.51xf.cn/mongo/mongo:3.4
        command: 
          - "bash"
          - "-c"
          - "numactl mongod -f /etc/conf.d/mongo.conf"
        volumeMounts:
        - name: mongo-data
          mountPath: /var/lib/mongodb
        - name: mongo-config
          mountPath: /etc/conf.d
        ports:
        - containerPort: 27017
      volumes:
      - name: mongo-config
        configMap:
          name: mongo-cm
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "mongo-cluster"
      resources:
        requests:
          storage: 4Gi