apiVersion: v1
kind: Service
metadata:
  name: 51xf_app-svc
  namespace: 51xf_namespace
spec:
  ports:
  - name: http-pub-port
    port: 8080
    targetPort: 8080
  selector:
    app: 51xf_app-dm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 51xf_app
  namespace: 51xf_namespace
spec:
  selector:
    matchLabels:
      app: 51xf_app-dm
  replicas: rc_no
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: 51xf_app-dm
        version: v-51xf_number
    spec:
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      containers:
      - name: 51xf_app-pod
        image: docker.51xf.cn/51xf/51xf_app:51xf_version
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "3072Mi"
            cpu: "2"
#        env:
#        - name: EGG_SERVER_ENV
#          value: 51xf_environment
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3