apiVersion: v1
kind: Service
metadata:
  name: smgpolicy-svc
  namespace: k8s-dev1
spec:
  type: NodePort
  ports:
  - name: http-pub-port
    port: 8080
    targetPort: 8080
  - name: http-private-port
    port: 9191
    targetPort: 9191
  selector:
    app: smgpolicy-dm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smgpolicy
  namespace: k8s-dev1
spec:
  selector:
    matchLabels:
      app: smgpolicy-dm
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: smgpolicy-dm
        version: v-51xf_number
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: smgpolicy-pod
        image: docker.51xf.cn/k8s/git:smgpolicy
        imagePullPolicy: Always
        env:
        - name: SMG_POLICY
          value: smg_policy_file
        - name: GIT_BRANCH
          value: branch          