- name: deploy static 
  hosts: '{{ host }}'
  gather_facts: false
  vars:
    src_dir: '{{ src_dir }}'
    dest_dir: '{{ dest_dir }}'
    app_user: app

  tasks:
#####判断相关的目录是否存在,不存在则创建
    - name: create directory if don't exist
      block:
      - name: "Checking directory"
        stat:
          path: "{{item}}"
        with_items:
          - ["/etc/ansible"]
        register: folder_stats
            
      - name: "creat multiple directory"
        file:
          path: "{{ item.item }}"
          state: directory
          mode: 0755
          group: "{{ app_user }}"
          owner: "{{ app_user }}"
        with_items:
         - "{{folder_stats.results}}"
        when: item.stat.exists == false
        
####同步静态文件
    - name: sync file
      synchronize:
        use_ssh_args: yes
        src: "{{ item }}/"
        dest: /etc/{{ dest_dir }}
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.idea"
          - "--exclude=.gitignore"
      with_items:
        - ["{{ src_dir }}"]
        

####修改文件属性 
    - name: chmod file
      file:
        path: /etc/ansible/key
        state: directory
        mode: 0600
        recurse: yes