- name: deploy project static 
  gather_facts: false
  hosts: '{{ host }}'
  remote_user: root
  vars:
    src_dir: '{{ src }}'
    dest_dir: '{{ dest }}'
  tasks:
  ####同步静态文件
    - name: sync file
      synchronize: 
        use_ssh_args: yes
        src: "{{ src_dir }}"
        dest: "{{ dest_dir }}"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.idea"
          - "--exclude=.gitignore"
