FROM docker.51xf.cn/centos/centos:7
MAINTAINER WangXiangYang <wangxiangyang@51xf.cn>

RUN set -xe \
&& yum -y install net-tools vim wget telnet curl rsync \
&& yum clean all \
&& localedef -c -f UTF-8 -i zh_CN zh_CN.UTF-8 \
&& cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo 'Asia/Shanghai' > /etc/timezone

ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh


ENV NODE_VERSION="8.14.0"

RUN set -xe \
&& yum -y install gcc make gcc-c++ openssl-devel wget \
&& yum clean all \
&& wget https://npm.taobao.org/mirrors/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz \
&& tar -xf node-v$NODE_VERSION-linux-x64.tar.gz -C /usr/local/ \
&& rm -fr node-v$NODE_VERSION-linux-x64.tar.gz \
&& ln -s /usr/local/node-v$NODE_VERSION-linux-x64/bin/node /usr/bin/node \
&& ln -s /usr/local/node-v$NODE_VERSION-linux-x64/bin/npm /usr/bin/npm \
&& npm config set registry https://registry.npm.taobao.org \
&& mkdir -p /opt/soft/logs/console_nodejs_service_logs \
&& mkdir -p /opt/soft/nodejs