apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-dev1-c0
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "redis-cluster"
    nfs:
      path: /k8s/dev1/redis/cluster/redis0
      server: 192.170.0.71

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-dev1-c1
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "redis-cluster"
    nfs:
      path: /k8s/dev1/redis/cluster/redis1
      server: 192.170.0.71