apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: cert-k8s-dev1
  spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: cert-k8s-dev1
    nfs:
      path: /k8s/k8s-dev1/cert/
      server: 192.192.0.79

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: data-cert-k8s-dev1
    namespace: k8s-dev1
  spec:
    storageClassName: cert-k8s-dev1
    accessModes:
      - ReadOnlyMany
    resources:
      requests:
        storage: 1Gi