apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: rocket-b-dev1-0
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "rocket-broker"
    hostPath:
      path: "/k8s/dev1/rocketmq/broker/0/"
      
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: rocket-b-dev1-1
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "rocket-broker"
    hostPath:
      path: "/k8s/dev1/rocketmq/broker/1/"

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: rocket-n-dev1-0
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "rocket-namesrv"
    hostPath:
      path: "/k8s/dev1/rocketmq/namesrv/0/"
      
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: rocket-n-dev1-1
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "rocket-namesrv"
    hostPath:
      path: "/k8s/dev1/rocketmq/namesrv/1/"