apiVersion: v1
kind: Service
metadata:
  name: rocketmq-svc
  namespace: dev1
spec:
  type: NodePort
  ports:
  - name: http-9876
    nodePort: 9876
    port: 9876
    targetPort: 9876
  - name: http-10911
    nodePort: 10911
    port: 10911
    targetPort: 10911
  - name: http-10912
    nodePort: 10912
    port: 10912
    targetPort: 10912
  - name: http-9595
    nodePort: 9595
    port: 9595
    targetPort: 9595
  selector:
    app: rocketmq-dm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq-deploy
  namespace: dev1
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: rocketmq-dm
    spec:
      containers:
      - name: broker
        image: docker.51xf.cn/rocketmq/rocketmq-broker:3.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 10911
          - containerPort: 10912
        volumeMounts:
          - mountPath: /opt/alibaba-rocketmq/logs
            name: brokeroptlogs
          - mountPath: /opt/alibaba-rocketmq/store
            name: brokeroptstore
      - name: namesrv
        image: docker.51xf.cn/rocketmq/rocketmq-namesrv:3.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9876
        volumeMounts:
          - mountPath: /opt/alibaba-rocketmq/logs
            name: namesrvoptlogs
          - mountPath: /opt/alibaba-rocketmq/store
            name: namesrvoptstore
      - name: console-ng
        image: docker.51xf.cn/rocketmq/rocketmq-console-ng:3.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9595
      volumes:
      - name: brokeroptlogs
        persistentVolumeClaim:
          claimName: rocket-b-pvc-0
      - name: brokeroptstore
        persistentVolumeClaim:
          claimName: rocket-b-pvc-1
      - name: namesrvoptlogs
        persistentVolumeClaim:
          claimName: rocket-n-pvc-0
      - name: namesrvoptstore
        persistentVolumeClaim:
          claimName: rocket-n-pvc-1